// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/auth/__root.tsx": {
    id: "routes/auth/__root";
    page: "/login";
  };
  "./routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_index": typeof import("./src/./routes/_index.tsx");
  "routes/auth/__root": typeof import("./src/./routes/auth/__root.tsx");
  "routes/auth/login": typeof import("./src/./routes/auth/login.tsx");
};