// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="../../node_modules/.bun/node_modules/uniwind/types.d.ts" />

declare module 'uniwind' {
  export interface UniwindConfig {
    themes: readonly ['light', 'dark']
  }
}
