name: Publish

on:
  push:
    tags:
      - '@rozumari/*@*.*.*'

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  FORCE_COLOR: 3
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  android:
    if: contains(github.ref, '@rozumari/mobile@')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: ./tools/github/actions/setup

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android
        uses: android-actions/setup-android@v4
        with:
          packages: platform-tools

      - name: Extract Tag Name and Version
        id: get_tag
        run: |
          TAG_NAME="${GITHUB_REF_NAME}"
          VERSION="${TAG_NAME##*@}"

          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "APP_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Setup EAS CLI
        env:
          EXPO_TOKEN: ${{ secrets:EXPO_TOKEN }}
        run: |
          bun install -g eas-cli

          eas whoami

      - name: Build APK
        working-directory: ./apps/mobile
        env:
          EXPO_TOKEN: ${{ secrets:EXPO_TOKEN }}
          EXPO_PUBLIC_API_URL: ${{ secrets.EXPO_PUBLIC_API_URL }}
          EXPO_PUBLIC_WEB_URL: ${{ secrets.EXPO_PUBLIC_WEB_URL }}
          EXPO_PUBLIC_TURNSTILE_KEY: ${{ secrets.EXPO_PUBLIC_TURNSTILE_KEY }}
        run: |
          mkdir -p ./build

          eas build \
            --output="./build/rozumari-v${{ env.APP_VERSION }}.apk" \
            --platform android \
            --profile production \
            --non-interactive \
            --local

      - name: Upload Build Artifacts to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          if compgen -G "apps/mobile/build/*" > /dev/null; then
            gh release upload "${{ env.TAG_NAME }}" \
              apps/mobile/build/rozumari-v${{ env.APP_VERSION }}.apk \
              --clobber
          else
            echo "No APK build artifact found, skipping upload."
            exit 1
          fi
