name: Publish

on:
  push:
    tags:
      - '@rozumari/web@*'
      - '@rozumari/api@*'

jobs:
  api:
    if: startsWith(github.ref, 'refs/tags/@rozumari/api@')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Deploy API to Vercel
        uses: amondnet/vercel-action@v42
        with:
          vercel-token: ${{ secrets.TURBO_TOKEN }}
          github-token: ${{ secrets.PAT_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_API_PROJECT_ID }}
          target: production

  web:
    if: startsWith(github.ref, 'refs/tags/@rozumari/web@')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Deploy Web to Vercel
        uses: amondnet/vercel-action@v42
        with:
          vercel-token: ${{ secrets.TURBO_TOKEN }}
          github-token: ${{ secrets.PAT_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_WEB_PROJECT_ID }}
          target: production
