name: Release

on:
  push:
    branches:
      - dev

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  FORCE_COLOR: 3
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./tools/github/actions/setup

      - name: Version & publish packages
        run: bun tegami ci
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
